name: uniswap_liquidity
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webon_kit_dart:
    path: packages/webon-kit-dart
  walletkit_dart:
    path: packages/walletkit-dart
  nomo_ui_kit: ^0.0.22
  google_fonts: 6.2.1
  nomo_router: ^0.0.3
  route_gen: 0.0.2
  collection: ^1.18.0
  logger: ^1.4.0
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.12
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
